#!/bin/sh
# nginx-yaml-entrypoint automatic configuration detection
# vim:sw=4:ts=4:et

set -e

# Function to merge multiple YAML files
merge_yaml_files() {
    local yaml_dir="$1"
    local output_file="$2"
    
    # Create a temporary merged file
    cat > "$output_file" << 'EOF'
# Merged YAML configuration from multiple files
# Auto-generated by nginx-yaml-entrypoint

EOF
    
    # Define file processing order
    local priority_files="global-config.yaml upstreams.yaml templates.yaml"
    local server_files="gportal-main.yaml gportal-photos.yaml gportal-files.yaml hitime.yaml"
    
    # Process priority files first (global, upstreams, templates)
    for file in $priority_files; do
        local full_path="$yaml_dir/$file"
        if [ -f "$full_path" ]; then
            echo "Merging: $file"
            echo "# --- Merged from $file ---" >> "$output_file"
            cat "$full_path" >> "$output_file"
            echo "" >> "$output_file"
        fi
    done
    
    # Add servers section header
    echo "# --- Server Configurations ---" >> "$output_file"
    echo "servers:" >> "$output_file"
    
    # Process server configuration files
    for file in $server_files; do
        local full_path="$yaml_dir/$file"
        if [ -f "$full_path" ]; then
            echo "Merging: $file"
            # Extract servers section and merge (remove the "servers:" line)
            sed '/^servers:/d' "$full_path" >> "$output_file"
            echo "" >> "$output_file"
        fi
    done
    
    # Process any remaining .yaml/.yml files not already processed
    for yaml_file in "$yaml_dir"/*.yaml "$yaml_dir"/*.yml; do
        if [ -f "$yaml_file" ]; then
            local basename=$(basename "$yaml_file")
            # Skip if already processed or if it's main.yaml
            if [ "$basename" != "main.yaml" ] && [ "$basename" != "global-config.yaml" ] && \
               [ "$basename" != "upstreams.yaml" ] && [ "$basename" != "templates.yaml" ] && \
               [ "$basename" != "gportal-main.yaml" ] && [ "$basename" != "gportal-photos.yaml" ] && \
               [ "$basename" != "gportal-files.yaml" ] && [ "$basename" != "hitime.yaml" ]; then
                echo "Merging additional file: $basename"
                echo "# --- Merged from $basename ---" >> "$output_file"
                cat "$yaml_file" >> "$output_file"
                echo "" >> "$output_file"
            fi
        fi
    done
}

# Function to process YAML files
process_yaml_configs() {
    local yaml_dir="/etc/nginx/yaml"
    local output_file="/etc/nginx/nginx.conf"
    local merged_yaml="/tmp/merged_config.yaml"
    local found_yaml=false
    
    echo "Scanning for YAML configurations in $yaml_dir..."
    
    if [ -d "$yaml_dir" ]; then
        # Check if we have multiple YAML files or just main.yaml
        local yaml_count=$(find "$yaml_dir" -name "*.yaml" -o -name "*.yml" | wc -l)
        
        if [ "$yaml_count" -gt 1 ]; then
            echo "Found multiple YAML files, merging them..."
            merge_yaml_files "$yaml_dir" "$merged_yaml"
            
            # Process the merged configuration
            echo "Converting merged YAML to nginx configuration..."
            if nginx-yaml-entrypoint -f "$merged_yaml" -o "$output_file" --verbose; then
                echo "Successfully generated nginx configuration from merged YAML files"
                found_yaml=true
            else
                echo "Failed to process merged YAML configuration"
            fi
        else
            # Look for single YAML file in priority order
            for yaml_file in "$yaml_dir/main.yaml" "$yaml_dir/nginx.yaml" "$yaml_dir/config.yaml" "$yaml_dir"/*.yaml "$yaml_dir"/*.yml; do
                if [ -f "$yaml_file" ]; then
                    echo "Found YAML configuration: $yaml_file"
                    
                    # Process the YAML file
                    echo "Converting YAML to nginx configuration..."
                    if nginx-yaml-entrypoint -f "$yaml_file" -o "$output_file" --verbose; then
                        echo "Successfully generated nginx configuration from $yaml_file"
                        found_yaml=true
                        break  # Use the first valid YAML file found
                    else
                        echo "Failed to process $yaml_file, trying next..."
                    fi
                fi
            done
        fi
    fi

    if [ "$found_yaml" = "true" ]; then
        # Validate the generated configuration
        echo "Validating generated nginx configuration..."
        if nginx -t; then
            echo "nginx configuration validation passed"
        else
            echo "nginx configuration validation failed"
            return 1
        fi
    else
        echo "No YAML configuration files found in $yaml_dir"
        echo "nginx will use existing configuration"
    fi
}

# Auto-detect and process YAML configurations
if command -v nginx-yaml-entrypoint >/dev/null 2>&1; then
    echo "nginx-yaml-entrypoint detected, processing YAML configurations..."
    process_yaml_configs
else
    echo "nginx-yaml-entrypoint not available, skipping YAML processing"
fi
