#!/bin/sh
# nginx-yaml-entrypoint automatic configuration detection
# vim:sw=4:ts=4:et

set -e

# Function to process YAML files
process_yaml_configs() {
    local yaml_dir="/etc/nginx/yaml"
    local output_file="/etc/nginx/nginx.conf"
    local found_yaml=false

    echo "Scanning for YAML configurations in $yaml_dir..."

    if [ -d "$yaml_dir" ]; then
        local yaml_files_found=0
        local temp_merged="/tmp/merged_nginx_config.yaml"
        
        # Count YAML files
        for yaml_file in "$yaml_dir"/*.yaml "$yaml_dir"/*.yml; do
            if [ -f "$yaml_file" ]; then
                yaml_files_found=$((yaml_files_found + 1))
            fi
        done
        
        if [ "$yaml_files_found" -eq 1 ]; then
            # Single file - process directly
            for yaml_file in "$yaml_dir/main.yaml" "$yaml_dir/nginx.yaml" "$yaml_dir/config.yaml" "$yaml_dir"/*.yaml "$yaml_dir"/*.yml; do
                if [ -f "$yaml_file" ]; then
                    echo "Found single YAML configuration: $yaml_file"
                    echo "Converting YAML to nginx configuration..."
                    if nginx-yaml-entrypoint -f "$yaml_file" -o "$output_file" --verbose; then
                        echo "Successfully generated nginx configuration from $yaml_file"
                        found_yaml=true
                        break
                    fi
                fi
            done
        elif [ "$yaml_files_found" -gt 1 ]; then
            # Multiple files - merge them first
            echo "Found $yaml_files_found YAML files, merging into one configuration..."
            
            # Create merged file header
            cat > "$temp_merged" << 'EOF'
# Merged YAML configuration from multiple files
# Auto-generated by nginx-yaml-entrypoint

EOF
            
            # Merge all YAML files (simple concatenation with separation)
            for yaml_file in "$yaml_dir"/*.yaml "$yaml_dir"/*.yml; do
                if [ -f "$yaml_file" ]; then
                    echo "Including: $(basename "$yaml_file")"
                    echo "# --- From $(basename "$yaml_file") ---" >> "$temp_merged"
                    cat "$yaml_file" >> "$temp_merged"
                    echo "" >> "$temp_merged"
                fi
            done
            
            # Process the merged file
            echo "Converting merged YAML to nginx configuration..."
            if nginx-yaml-entrypoint -f "$temp_merged" -o "$output_file" --verbose; then
                echo "Successfully generated nginx configuration from $yaml_files_found merged files"
                found_yaml=true
            else
                echo "Failed to process merged YAML configuration"
            fi
            
            # Clean up temp file
            rm -f "$temp_merged"
        fi
    fi

    if [ "$found_yaml" = "true" ]; then
        # Validate the generated configuration
        echo "Validating generated nginx configuration..."
        if nginx -t; then
            echo "nginx configuration validation passed"
        else
            echo "nginx configuration validation failed"
            return 1
        fi
    else
        echo "No YAML configuration files found in $yaml_dir"
        echo "nginx will use existing configuration"
    fi
}

# Auto-detect and process YAML configurations
if command -v nginx-yaml-entrypoint >/dev/null 2>&1; then
    echo "nginx-yaml-entrypoint detected, processing YAML configurations..."
    process_yaml_configs
else
    echo "nginx-yaml-entrypoint not available, skipping YAML processing"
fi
